## Some very basic concepts of tensorflow:

In [5]:
# choose tensorflow version 2.12.0 for this project
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.15.0


In [6]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
# check the number of dimensions of a tensor
scalar.ndim

0

In [8]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [10]:
# check the number of dimensions of a vector
vector.ndim

1

In [16]:
# create a matrix in which has 1 more dimension
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [17]:
matrix.ndim

2

In [24]:
# create another matrix in which has 1 more dimension, with float16 data type as it takes less memory
matrix2 = tf.constant([[10., 7.],
                       [7., 10.],
                       [3., 2.]], dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 3.,  2.]], dtype=float16)>

In [26]:
# create a tensor with more than 2 dimensions
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]],
                     [[13, 14, 15],
                      [16, 17, 18]]])
tensor.ndim # this is a 3-dimensional tensor

3